name: github action tag release 

on:
  push:
    branches:
      - main

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Create Tag
      id: tag
      uses: anothrNick/github-tag-action@1.70.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release_branches: "release.*"
  
    - name: Create a GitHub release uplus
      uses: ncipollo/release-action@v1 
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}-uplus
        name: ${{ steps.tag_version.outputs.new_tag }}-uplus
        generateReleaseNotes: true
    
    - name: Create a GitHub release torder
      uses: ncipollo/release-action@v1 
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}-torder
        name: ${{ steps.tag_version.outputs.new_tag }}-torder
        generateReleaseNotes: true
